const FIRM_NAME = "{FIRM_NAME}";
const FIRM_PHONE_NUMBER = "{FIRM_PHONE_NO}";
const FIRM_ADDRESS = "{FIRM_ADDRESS}";
const FIRM_GSTIN = "{FIRM_GSTIN}";
const FIRM_STATE = "{FIRM_STATE}";
const FIRM_EMAIL = "{FIRM_EMAIL}";

const BAYER_NAME = "{BAYER_NAME}";
const SITE_ADDRESS = "{SITE_ADDRESS}";
const BAYER_GSTIN = "{BAYER_GSTIN}";
const BAYER_STATE = "{BAYER_STATE}";
const BAYER_EMAIL = "{BAYER_EMAIL}";

const INVOICE_NO = "{INVOICE_NO}";
const INVOICE_DATE = "{INVOICE_NO}";

const SR_NO_COL = "{SR_NOS}";
const PARTICULARS_COL = "{PARTICULARS}";
const HSN_CODE_COL = "{HSN_CODES}";
const QUANTITY_COL = "{QUANTITY_COL}";
const RATE_COL = "{RATE_COL}";
const PER_COL = "{PER_COL}";
const AMOUNTS_COL = "{AMOUNTS_COL}";

const TOTAL_AMOUNT = "{TOTAL_AMOUNT}";
const CGST_VALUE = "{CGST_VALUE}";
const SGST_VALUE = "{SGST_VALUE}";
const ROUNDUP_VALUE = "{ROUNDUP_VALUE}";
const GRAND_TOTAL_VALUE = "{GRAND_TOTAL_VALUE}";
const GRAND_TOTAL_IN_WORDS = "{GRAND_TOTAL_IN_WORDS}";

const BANK_OWNER_NAME = "{BANK_OWNER_NAME}";
const BANK_ACCOUNT_NUMBER = "{BANK_ACCOUNT_NO}";
const BANK_IFSC_CODE = "{IFSC_CODE}";
const BANK_NAME = "{BANK_NAME}";
const BANK_BRANCH_NAME = "{BANK_BRANCH_NAME}";

const CITY_NAME = "{CITY_NAME}";
